### ISSUE TITLE
Got error when running evaluation.py

### ISSUE THREAD

**Issue by Yu-Jiawei** [OpenDriveLab/DriveLM#98]
When I run evaluation.py, I meet the error as follows:
Traceback (most recent call last):
  File "evaluation.py", line 188, in <module>
    output = evaluation.evaluation()
  File "evaluation.py", line 145, in evaluation
    scores["chatgpt"] = self.eval_chatGPT(self.GPT)
  File "evaluation.py", line 38, in eval_chatGPT
    scores = p.map(self.chatgpt_eval.forward, data)
  File "/root/miniconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/miniconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/root/miniconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/root/miniconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/root/miniconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object

**Comment by ChonghaoSima** [comment]
seems like bug in mpi, try decreasing the number of process in the process pool.

**Comment by davidpengiupui** [comment]
same problem. May I know how you solve this bug?

**Comment by Cynthia11281128** [comment]
Same problem, did you solve it
